### ISSUE TITLE
No one gets registered

### ISSUE THREAD

**Issue by klick** [bossanova808/CommerceRegisterOnCheckout#10]
The only log messages I get are: `[Forced]`.

I am a bit confused. Using you sample code: how and when does the POST request get triggered? Don’t know where to start, really. Any pointers?

**Comment by bossanova808** [comment]
Ok, so you need to implement the POST wherever you need it for your checkout flow.  

In my case, I piggy back it on the payment submission form...i.e. I intercept the submit, manually POST to this controller, and then let it fall through to the normal form submission.

Wherever your form happens to end up (in my case the order complete page) - you should then handle success/errors with the registration process.

Happy to help in a bit more detail if you find me on slack (@jeremydaalder)

**Comment by klick** [comment]
Ha. Just wanted to answer… Haven’t read the docs properly (long day) and figured it out later. My bad!

Thanks for replying!
