### ISSUE TITLE
FR: Allow registration after order is placed

### ISSUE THREAD

**Issue by terraindesign** [bossanova808/CommerceRegisterOnCheckout#18]
In the current checkout workflow, we provide a (non-plugin based) ajax registration form on the order confirmation page (along with an order-invoice), with pre-filled hidden fields for firstName, lastName, and email from the order, so that all the user needs to enter is password. However, as you mention, the shipping and billing address is not currently saved to the customer account. Thus the interest in this great plugin. 

However, if I understand correctly, this plugin will only work if registration is done during the checkout process, before payment is completed? It would be great if it would also work after the checkout process is completed, or anytime that there is a 'order' model available.

fyi... this is for a craft 3/commerce 2 implementation (you don't seem to have 'Issues' enabled for that fork.)

**Comment by bossanova808** [comment]
You'll want to pass this feedback/idea on to Luke Holder at P & T as CROC is being folded into core (or, re-implemented most likely) as part of the Commerce 2 release.

Unless that decision changes, CROC is essentially an on hold legacy plugin at this point for Commerce V1 and I won't be doing anything new with it I'm afraid.

(Feel free to crib the code for your own needs - in short - basically listen to the registration event, I guess, and then grab the addresses and copy them to the new user basically as this plugin does).

**Comment by terraindesign** [comment]
Thanks for the update, and for pointing me in the right direction. Cheers.
