### ISSUE TITLE
Error after plugin install

### ISSUE THREAD

**Issue by 8cylinder** [bossanova808/CommerceRegisterOnCheckout#2]
This plugin looks like exactly what I need, but I've run into an error.

After installing the plugin but before any code has been added to the templates, this error happens when going through the checkout process on a fresh install of Craft Commerce (version 2.6.2959). 

`CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft.craft_commerceregisteroncheckout' doesn't exist. The SQL statement executed was: select * from craft_commerceregisteroncheckout where orderNumber='df410f931c1af96c06f88b3342146300'`

This is on the `shop/checkout/payment` page.

Should I manually create the table it's asking for?

**Comment by bossanova808** [comment]
Yeah that is my bad.  I moved some code into a migration to change a table, when I changed how this works, but I appear to have forgotten to put the bit in that installs the table - sorry!

I'll do a fix now.  You'll need to grab the new version (once I close this) - and then uninstall and re-install it to trigger the table creation.

**Comment by bossanova808** [comment]
Hey

If you grab master from https://github.com/bossanova808/CommerceRegisterOnCheckout - can you give that a try?  It's a bit awkward for me to test it right now but it should be fine.  Let me know then i can push it out properly.

**Comment by 8cylinder** [comment]
Thanks, that fixed it!  
The table gets created when installing.
