### ISSUE TITLE
Custom DB prefix not working

### ISSUE THREAD

**Issue by olsp** [bossanova808/CommerceRegisterOnCheckout#5]
I just wanted to install the plugin but got the following error message: 
`CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd0227279.craft_commerceregisteroncheckout' doesn't exist`

In my config/db.php I set a custom prefix, which is not 'craft' - it seems like the plugins does not take care of this.

**Comment by bossanova808** [comment]
Yep that's a bug. 

I have some minor fixes to do so son, will add this to the list.  In the meantime if you change the prefix in the add-on code that should get you started.... Sorry!

**Comment by bossanova808** [comment]
Should be fixed in the latest:
https://github.com/bossanova808/CommerceRegisterOnCheckout/releases/tag/0.0.7
